#pragma once
#include "CoreMinimal.h"
 
//Camera
#define DEFAULT_CAMERA_MOVE_DISTANCE 500
#define DEFAULT_CAMERA_MOVE_SPEED 700
#define MAX_CAMERA_MOVE_SPEED 1500
#define DEFAULT_CAMERA_ZOOM_DISTANCE 900
#define MAX_CAMERA_ZOOM_DISTANCE 2000
#define MIN_CAMERA_ZOOM_DISTANCE 500
#define CAMERA_ZOOM_SPEED 50
#define DEFAULT_LOADOUT_CAMERA_ISTANCE 720

#define INPUT_CLICKED_WAIT_TIME 0.5
#define INPUT_CLICKED_MOVE_DISTANCE 20

//Bullet
#define BULLET_DISAPPEAR_SPEED 5000

//Gun Speed
#define BULLET_MOVE_SPEED 1200

//Arrow Speed
#define ARROW_MOVE_SPEED 1600

//Agent
#define HERO_WEAPON_SOCKET "weapon"
#define HERO_ATTACK_ROTATE_SPEED 640
#define HERO_ATTACK_LOCK_TIME 5.0
#define HERO_OUTLINE_DEPTH_INDEX 0
#define ENEMY_OUTLINE_DEPTH_INDEX 1
#define UPDATE_BLOOD_SPEED 50

//HUD
#define HP_BAR_SCALE 0.75
#define HUD_DEFAULT_MAX_HP 1000
#define HUD_DEFAULT_HP 100

//Show Hurt 
#define SHOW_HURT_DISAPPEAR_TIME 0.8
#define SHOW_HURT_UP_SPEED 10
#define SHOW_HURT_SCALE 0.3

//Mini map
#define MAX_MINIMAP_DRAW_STEP_COUNT 36
#define DEFAULT_MINIMAP_MINIMAP_SIZE_RATE 0.16

//Role Switch 
#define SWITCH_HERO_ROT_SPEED 720
